### ISSUE TITLE
./matrix_multiply.whiley:1: expected end-of-line import std.ascii

### ISSUE THREAD

**Issue by sammaphey** [Whiley/WhileyDevelopmentKit#2]
Attempting to run the example code and run into this error. 

It seems that in some of the examples in order to import this is used: 
`std::io`

while in others this is used:
`std.io`

which should be preffered?

**Comment by DavePearce** [comment]
Hey Sam,

`std::io` is the new syntax.  Ugh, I can see that the examples in the `wdk-v0.4.2.tgz` have not all been updated.  That's annoying as I thought I did that!!

Ok, something to fix...

**Comment by sammaphey** [comment]
Always things to do and never enough time to do it!

**Comment by DavePearce** [comment]
Ok, should be fixed now.
