### ISSUE TITLE
Directions to set WHILEYHOME need to be in more places

### ISSUE THREAD

**Issue by WalkerCodeRanger** [Whiley/WhileyDevelopmentKit#3]
The readme file for this repo says "Then set the WHILEYHOME environment variable to the directory of the unpacked tarball." However, these instructions don't appear on http://whiley.org/downloads/ where I downloaded the development kit from. They don't appear in the wdk-v0.4.2 package I downloaded. Not even in the installation section of the getting started PDF in the development kit.

I recommend adding an INSTALL.txt or README.txt to the root of the wdk that includes these instructions.

**Comment by DavePearce** [comment]
Hey Jeff,

Ok, that sounds like a pretty reasonable plan ... let's add a README to the wdk tarball.  That would really help!!
